package pokemon.pokemons;

import pokemon.*;
import pokemon.properties.PokemonMove;
import pokemon.properties.PokemonMoves;
import pokemon.properties.PokemonType;
import pokemon.properties.PokemonTypes;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static pokemon.properties.PokemonTypes.*;
import static pokemon.properties.PokemonMoves.*;

public class KalosPokemon {
    public static List<Pokemon> kalosPokemons = new ArrayList<>();
    public static Pokemon CHESPIN = KalosPokemon.register(650, "chespin", 4, 56, 61, 65, 38, 63, Arrays.asList(GRASS), Arrays.asList(WORK_UP, ATTRACT, SUBSTITUTE, ATTRACT), Arrays.asList(VINE_WHIP, VINE_WHIP, WOOD_HAMMER, SYNTHESIS), Arrays.asList());
    public static Pokemon QUILLADIN = KalosPokemon.register(651, "quilladin", 7, 61, 78, 95, 57, 142, Arrays.asList(GRASS), Arrays.asList(SLEEP_TALK, HIDDEN_POWER, ENDURE, TAKE_DOWN), Arrays.asList(LEAF_STORM, LEECH_SEED, WOOD_HAMMER, GIGA_DRAIN), Arrays.asList());
    public static Pokemon CHESNAUGHT = KalosPokemon.register(652, "chesnaught", 16, 88, 107, 122, 64, 239, Arrays.asList(GRASS, FIGHTING), Arrays.asList(SUPER_FANG, BLOCK, GROWL, PAIN_SPLIT), Arrays.asList(SYNTHESIS, SEED_BOMB, WOOD_HAMMER, SYNTHESIS), Arrays.asList(LOW_KICK, FOCUS_PUNCH, QUICK_GUARD, ROCK_SMASH));
    public static Pokemon FENNEKIN = KalosPokemon.register(653, "fennekin", 4, 40, 45, 40, 60, 61, Arrays.asList(FIRE), Arrays.asList(ATTRACT, CONFIDE, ENDURE, ATTRACT), Arrays.asList(INCINERATE, EMBER, INCINERATE, FLARE_BLITZ), Arrays.asList());
    public static Pokemon BRAIXEN = KalosPokemon.register(654, "braixen", 10, 59, 59, 58, 73, 143, Arrays.asList(FIRE), Arrays.asList(PROTECT, LUCKY_CHANT, SWIFT, ATTRACT), Arrays.asList(FLARE_BLITZ, EMBER, WILL_O_WISP, HEAT_WAVE), Arrays.asList());
    public static Pokemon DELPHOX = KalosPokemon.register(655, "delphox", 15, 75, 69, 72, 104, 240, Arrays.asList(FIRE, PokemonTypes.PSYCHIC), Arrays.asList(CONFIDE, PSYCH_UP, SWIFT, HIDDEN_POWER), Arrays.asList(INCINERATE, FIRE_PLEDGE, FLAME_CHARGE, BLAST_BURN), Arrays.asList(MAGIC_COAT, LIGHT_SCREEN, REST, PokemonMoves.PSYCHIC));
    public static Pokemon FROAKIE = KalosPokemon.register(656, "froakie", 3, 41, 56, 40, 71, 63, Arrays.asList(WATER), Arrays.asList(PROTECT, SUBSTITUTE, GROWL, SLEEP_TALK), Arrays.asList(RAIN_DANCE, BUBBLE, WATER_PULSE, BUBBLE), Arrays.asList());
    public static Pokemon FROGADIER = KalosPokemon.register(657, "frogadier", 6, 54, 63, 52, 97, 142, Arrays.asList(WATER), Arrays.asList(FRUSTRATION, WORK_UP, SLEEP_TALK, DOUBLE_TEAM), Arrays.asList(HYDRO_PUMP, DIVE, WATER_PULSE, SURF), Arrays.asList());
    public static Pokemon GRENINJA = KalosPokemon.register(658, "greninja", 15, 72, 95, 67, 122, 239, Arrays.asList(WATER, DARK), Arrays.asList(SWIFT, DOUBLE_TEAM, WORK_UP, HYPER_BEAM), Arrays.asList(HYDRO_CANNON, WATER_PLEDGE, WATER_PULSE, DIVE), Arrays.asList(FEINT_ATTACK, NIGHT_SLASH, SWITCHEROO, NIGHT_SLASH));
    public static Pokemon BUNNELBY = KalosPokemon.register(659, "bunnelby", 4, 38, 36, 38, 57, 47, Arrays.asList(NORMAL), Arrays.asList(ENDEAVOR, DEFENSE_CURL, ENDEAVOR, DOUBLE_SLAP), Arrays.asList(), Arrays.asList());
    public static Pokemon DIGGERSBY = KalosPokemon.register(660, "diggersby", 10, 85, 56, 77, 78, 148, Arrays.asList(NORMAL, GROUND), Arrays.asList(SUPER_FANG, SECRET_POWER, STRENGTH, CUT), Arrays.asList(), Arrays.asList(BULLDOZE, EARTH_POWER, SPIKES, SPIKES));
    public static Pokemon FLETCHLING = KalosPokemon.register(661, "fletchling", 3, 45, 50, 43, 62, 56, Arrays.asList(NORMAL, FLYING), Arrays.asList(SWORDS_DANCE, DOUBLE_TEAM, TAKE_DOWN, TACKLE), Arrays.asList(), Arrays.asList(AERIAL_ACE, ROOST, AIR_SLASH, DEFOG));
    public static Pokemon FLETCHINDER = KalosPokemon.register(662, "fletchinder", 7, 62, 73, 55, 84, 134, Arrays.asList(FIRE, FLYING), Arrays.asList(FLAIL, SNORE, FACADE, FACADE), Arrays.asList(EMBER, FLAME_CHARGE, INCINERATE, FLAME_CHARGE), Arrays.asList(ACROBATICS, BRAVE_BIRD, PECK, HURRICANE));
    public static Pokemon TALONFLAME = KalosPokemon.register(663, "talonflame", 12, 78, 81, 71, 126, 175, Arrays.asList(FIRE, FLYING), Arrays.asList(SUBSTITUTE, QUICK_ATTACK, ATTRACT, SLEEP_TALK), Arrays.asList(WILL_O_WISP, FIRE_BLAST, FLAMETHROWER, FIRE_BLAST), Arrays.asList(DEFOG, DEFOG, ROOST, FEATHER_DANCE));
    public static Pokemon SCATTERBUG_ICY_SNOW = KalosPokemon.register(664, "scatterbug_icy_snow", 3, 38, 35, 40, 35, 40, Arrays.asList(BUG), Arrays.asList(TACKLE), Arrays.asList(BUG_BITE, STRUGGLE_BUG, RAGE_POWDER, BUG_BITE), Arrays.asList());
    public static Pokemon SPEWPA_ICY_SNOW = KalosPokemon.register(665, "spewpa_icy_snow", 3, 45, 22, 60, 29, 75, Arrays.asList(BUG), Arrays.asList(HARDEN, PROTECT, PROTECT, PROTECT), Arrays.asList(STRUGGLE_BUG, BUG_BITE, BUG_BITE, BUG_BITE), Arrays.asList());
    public static Pokemon VIVILLON_MEADOW = KalosPokemon.register(666, "vivillon_meadow", 12, 80, 52, 50, 89, 185, Arrays.asList(BUG, FLYING), Arrays.asList(SUPERSONIC, SNORE, SWAGGER, DOUBLE_TEAM), Arrays.asList(U_TURN, INFESTATION, STRUGGLE_BUG, QUIVER_DANCE), Arrays.asList(ACROBATICS, AERIAL_ACE, ACROBATICS, AERIAL_ACE));
    public static Pokemon LITLEO = KalosPokemon.register(667, "litleo", 6, 62, 50, 58, 72, 74, Arrays.asList(FIRE, NORMAL), Arrays.asList(SLEEP_TALK, SWAGGER, YAWN, ROAR), Arrays.asList(FIRE_SPIN, FLAMETHROWER, OVERHEAT, EMBER), Arrays.asList());
    public static Pokemon PYROAR = KalosPokemon.register(668, "pyroar", 15, 86, 68, 72, 106, 177, Arrays.asList(FIRE, NORMAL), Arrays.asList(SLEEP_TALK, ENDURE, RETURN, HELPING_HAND), Arrays.asList(EMBER, OVERHEAT, FLAME_CHARGE, HEAT_WAVE), Arrays.asList());
    public static Pokemon FLABEBE_RED = KalosPokemon.register(669, "flabebe_red", 1, 44, 38, 39, 42, 61, Arrays.asList(FAIRY), Arrays.asList(SECRET_POWER, NATURE_POWER, CONFIDE, COVET), Arrays.asList(FAIRY_WIND, MISTY_TERRAIN, DISARMING_VOICE, MISTY_TERRAIN), Arrays.asList());
    public static Pokemon FLOETTE_RED = KalosPokemon.register(670, "floette_red", 2, 54, 45, 47, 52, 130, Arrays.asList(FAIRY), Arrays.asList(CONFIDE, SAFEGUARD, PROTECT, HEAL_BELL), Arrays.asList(FAIRY_WIND, FAIRY_WIND, MISTY_TERRAIN, DRAINING_KISS), Arrays.asList());
    public static Pokemon FLORGES_RED = KalosPokemon.register(671, "florges_red", 11, 78, 65, 68, 75, 248, Arrays.asList(FAIRY), Arrays.asList(GIGA_IMPACT, ATTRACT, SUBSTITUTE, WISH), Arrays.asList(DRAINING_KISS, DISARMING_VOICE, DISARMING_VOICE, MISTY_TERRAIN), Arrays.asList());
    public static Pokemon SKIDDO = KalosPokemon.register(672, "skiddo", 9, 66, 65, 48, 52, 70, Arrays.asList(GRASS), Arrays.asList(SUBSTITUTE, ROAR, CONFIDE, RETALIATE), Arrays.asList(MAGICAL_LEAF, ENERGY_BALL, LEAF_STORM, MAGICAL_LEAF), Arrays.asList());
    public static Pokemon GOGOAT = KalosPokemon.register(673, "gogoat", 17, 123, 100, 62, 68, 186, Arrays.asList(GRASS), Arrays.asList(STRENGTH, RETURN, RETALIATE, WORK_UP), Arrays.asList(BULLET_SEED, SEED_BOMB, LEECH_SEED, MAGICAL_LEAF), Arrays.asList());
    public static Pokemon PANCHAM = KalosPokemon.register(674, "pancham", 6, 67, 82, 62, 43, 70, Arrays.asList(FIGHTING), Arrays.asList(FACADE, CONFIDE, SUBSTITUTE, CONFIDE), Arrays.asList(CIRCLE_THROW, CIRCLE_THROW, ROCK_SMASH, LOW_SWEEP), Arrays.asList());
    public static Pokemon PANGORO = KalosPokemon.register(675, "pangoro", 21, 95, 124, 78, 58, 173, Arrays.asList(FIGHTING, DARK), Arrays.asList(COMET_PUNCH, TACKLE, ATTRACT, RETURN), Arrays.asList(KARATE_CHOP, KARATE_CHOP, CLOSE_COMBAT, ROCK_SMASH), Arrays.asList(CRUNCH, THIEF, DARK_PULSE, TORMENT));
    public static Pokemon FURFROU_NATURAL = KalosPokemon.register(676, "furfrou_natural", 12, 75, 80, 60, 102, 165, Arrays.asList(NORMAL), Arrays.asList(ROUND, CONFIDE, ENDEAVOR, TAKE_DOWN), Arrays.asList(), Arrays.asList());
    public static Pokemon ESPURR = KalosPokemon.register(677, "espurr", 3, 62, 48, 54, 68, 71, Arrays.asList(PokemonTypes.PSYCHIC), Arrays.asList(ECHOED_VOICE, FLASH, CONFIDE, ENDURE), Arrays.asList(GRAVITY, TRICK, ZEN_HEADBUTT, BARRIER), Arrays.asList());
    public static Pokemon MEOWSTIC_MALE = KalosPokemon.register(678, "meowstic_male", 6, 74, 48, 76, 104, 163, Arrays.asList(PokemonTypes.PSYCHIC), Arrays.asList(SWAGGER, ENDURE, FRUSTRATION, CUT), Arrays.asList(MAGIC_ROOM, ZEN_HEADBUTT, ZEN_HEADBUTT, TRICK), Arrays.asList());
    public static Pokemon HONEDGE = KalosPokemon.register(679, "honedge", 8, 45, 80, 100, 28, 65, Arrays.asList(STEEL, GHOST), Arrays.asList(SLEEP_TALK, SLEEP_TALK, BLOCK, RETALIATE), Arrays.asList(GYRO_BALL, IRON_DEFENSE, GYRO_BALL, METAL_SOUND), Arrays.asList(SPITE, DESTINY_BOND, SHADOW_CLAW, SHADOW_SNEAK));
    public static Pokemon DOUBLADE = KalosPokemon.register(680, "doublade", 8, 59, 110, 150, 35, 157, Arrays.asList(STEEL, GHOST), Arrays.asList(TACKLE, PROTECT, SNORE, SLASH), Arrays.asList(IRON_HEAD, IRON_HEAD, METAL_SOUND, FLASH_CANNON), Arrays.asList(SPITE, SPITE, SPITE, SPITE));
    public static Pokemon AEGISLASH_SHIELD = KalosPokemon.register(681, "aegislash_shield", 17, 60, 50, 140, 60, 250, Arrays.asList(STEEL, GHOST), Arrays.asList(SWAGGER, TACKLE, CONFIDE, CONFIDE), Arrays.asList(IRON_HEAD, IRON_HEAD, IRON_DEFENSE, IRON_DEFENSE), Arrays.asList(SHADOW_CLAW, SPITE, SHADOW_BALL, SPITE));
    public static Pokemon SPRITZEE = KalosPokemon.register(682, "spritzee", 2, 78, 52, 60, 23, 68, Arrays.asList(FAIRY), Arrays.asList(HELPING_HAND, HIDDEN_POWER, ENDURE, PSYCH_UP), Arrays.asList(SWEET_KISS, DAZZLING_GLEAM, MISTY_TERRAIN, MISTY_TERRAIN), Arrays.asList());
    public static Pokemon AROMATISSE = KalosPokemon.register(683, "aromatisse", 8, 101, 72, 72, 29, 162, Arrays.asList(FAIRY), Arrays.asList(ATTRACT, FLAIL, HIDDEN_POWER, CONFIDE), Arrays.asList(DISARMING_VOICE, MISTY_TERRAIN, CHARM, DISARMING_VOICE), Arrays.asList());
    public static Pokemon SWIRLIX = KalosPokemon.register(684, "swirlix", 4, 62, 48, 66, 49, 68, Arrays.asList(FAIRY), Arrays.asList(PLAY_NICE, ENDEAVOR, PSYCH_UP, SAFEGUARD), Arrays.asList(CHARM, DRAINING_KISS, CHARM, FAIRY_WIND), Arrays.asList());
    public static Pokemon SLURPUFF = KalosPokemon.register(685, "slurpuff", 8, 82, 80, 86, 72, 168, Arrays.asList(FAIRY), Arrays.asList(HELPING_HAND, WISH, ROUND, ROUND), Arrays.asList(CHARM, DAZZLING_GLEAM, DRAINING_KISS, FAIRY_WIND), Arrays.asList());
    public static Pokemon INKAY = KalosPokemon.register(686, "inkay", 4, 53, 54, 53, 45, 58, Arrays.asList(DARK, PokemonTypes.PSYCHIC), Arrays.asList(RETURN, ENDURE, FACADE, RETALIATE), Arrays.asList(FLING, FOUL_PLAY, TORMENT, FLATTER), Arrays.asList(STORED_POWER, STORED_POWER, ROLE_PLAY, SKILL_SWAP));
    public static Pokemon MALAMAR = KalosPokemon.register(687, "malamar", 15, 86, 92, 88, 73, 169, Arrays.asList(DARK, PokemonTypes.PSYCHIC), Arrays.asList(ACUPRESSURE, SWIFT, BIND, DOUBLE_TEAM), Arrays.asList(DARK_PULSE, SNATCH, TORMENT, TOPSY_TURVY), Arrays.asList(LIGHT_SCREEN, TELEKINESIS, PSYWAVE, TRICK_ROOM));
    public static Pokemon BINACLE = KalosPokemon.register(688, "binacle", 5, 42, 52, 67, 50, 61, Arrays.asList(ROCK, WATER), Arrays.asList(SWORDS_DANCE, ATTRACT, HELPING_HAND, FALSE_SWIPE), Arrays.asList(STEALTH_ROCK, ROCK_BLAST, ROCK_SLIDE, ROCK_SLIDE), Arrays.asList(WATER_GUN, WATER_SPORT, CLAMP, WATER_SPORT));
    public static Pokemon BARBARACLE = KalosPokemon.register(689, "barbaracle", 13, 72, 105, 115, 68, 175, Arrays.asList(ROCK, WATER), Arrays.asList(CONFIDE, HYPER_BEAM, FURY_SWIPES, SWORDS_DANCE), Arrays.asList(ROCK_SLIDE, STONE_EDGE, STEALTH_ROCK, ROCK_TOMB), Arrays.asList(DIVE, SURF, CLAMP, WATER_GUN));
    public static Pokemon SKRELP = KalosPokemon.register(690, "skrelp", 5, 50, 60, 60, 30, 64, Arrays.asList(POISON, WATER), Arrays.asList(PROTECT, HIDDEN_POWER, SUBSTITUTE, SWAGGER), Arrays.asList(VENOM_DRENCH, TOXIC, ACID, TOXIC), Arrays.asList(WATER_PULSE, SCALD, WATER_GUN, SURF));
    public static Pokemon DRAGALGE = KalosPokemon.register(691, "dragalge", 18, 65, 75, 90, 44, 173, Arrays.asList(POISON, DRAGON), Arrays.asList(ROUND, SWAGGER, FRUSTRATION, SECRET_POWER), Arrays.asList(ACID, VENOSHOCK, VENOM_DRENCH, VENOM_DRENCH), Arrays.asList(DRAGON_PULSE, OUTRAGE, DRAGON_TAIL, OUTRAGE));
    public static Pokemon CLAUNCHER = KalosPokemon.register(692, "clauncher", 5, 50, 53, 62, 44, 66, Arrays.asList(WATER), Arrays.asList(FLAIL, ENDURE, ENDURE, SNORE), Arrays.asList(DIVE, WATER_SPORT, DIVE, WATER_GUN), Arrays.asList());
    public static Pokemon CLAWITZER = KalosPokemon.register(693, "clawitzer", 13, 71, 73, 88, 59, 100, Arrays.asList(WATER), Arrays.asList(FRUSTRATION, DOUBLE_TEAM, VICE_GRIP, SCARY_FACE), Arrays.asList(HYDRO_PUMP, SCALD, BUBBLE_BEAM, BUBBLE), Arrays.asList());
    public static Pokemon HELIOPTILE = KalosPokemon.register(694, "helioptile", 5, 44, 38, 33, 70, 58, Arrays.asList(ELECTRIC, NORMAL), Arrays.asList(CAMOUFLAGE, CUT, ATTRACT, ROUND), Arrays.asList(ELECTRO_BALL, ELECTRO_BALL, PARABOLIC_CHARGE, ELECTROWEB), Arrays.asList());
    public static Pokemon HELIOLISK = KalosPokemon.register(695, "heliolisk", 10, 62, 55, 52, 109, 168, Arrays.asList(ELECTRIC, NORMAL), Arrays.asList(PSYCH_UP, CONFIDE, MEGA_KICK, SLEEP_TALK), Arrays.asList(CHARGE, CHARGE_BEAM, ELECTRIC_TERRAIN, ELECTRIFY), Arrays.asList());
    public static Pokemon TYRUNT = KalosPokemon.register(696, "tyrunt", 8, 58, 89, 77, 48, 72, Arrays.asList(ROCK, DRAGON), Arrays.asList(BIDE, PROTECT, HIDDEN_POWER, THRASH), Arrays.asList(STEALTH_ROCK, ROCK_SLIDE, STONE_EDGE, ROCK_THROW), Arrays.asList(DRAGON_TAIL, DRACO_METEOR, DRAGON_CLAW, OUTRAGE));
    public static Pokemon TYRANTRUM = KalosPokemon.register(697, "tyrantrum", 25, 82, 121, 119, 71, 182, Arrays.asList(ROCK, DRAGON), Arrays.asList(STOMP, GIGA_IMPACT, ENDURE, SUBSTITUTE), Arrays.asList(ROCK_POLISH, STEALTH_ROCK, ROCK_SLIDE, ROCK_TOMB), Arrays.asList(OUTRAGE, DRACO_METEOR, DRAGON_CLAW, DRACO_METEOR));
    public static Pokemon AMAURA = KalosPokemon.register(698, "amaura", 13, 77, 59, 50, 46, 72, Arrays.asList(ROCK, ICE), Arrays.asList(SECRET_POWER, FLASH, BODY_SLAM, ROAR), Arrays.asList(SANDSTORM, ROCK_TOMB, ANCIENT_POWER, ROCK_THROW), Arrays.asList(BLIZZARD, HAZE, FROST_BREATH, HAZE));
    public static Pokemon AURORUS = KalosPokemon.register(699, "aurorus", 27, 123, 77, 72, 58, 104, Arrays.asList(ROCK, ICE), Arrays.asList(HIDDEN_POWER, ROUND, PSYCH_UP, ENCORE), Arrays.asList(SANDSTORM, ROCK_SLIDE, ANCIENT_POWER, STEALTH_ROCK), Arrays.asList(POWDER_SNOW, AURORA_BEAM, POWDER_SNOW, AVALANCHE));
    public static Pokemon SYLVEON = KalosPokemon.register(700, "sylveon", 10, 95, 65, 65, 60, 184, Arrays.asList(FAIRY), Arrays.asList(DOUBLE_TEAM, PROTECT, SLEEP_TALK, ROUND), Arrays.asList(FAIRY_WIND, MISTY_TERRAIN, DRAINING_KISS, DRAINING_KISS), Arrays.asList());
    public static Pokemon HAWLUCHA = KalosPokemon.register(701, "hawlucha", 8, 78, 92, 75, 118, 175, Arrays.asList(FIGHTING, FLYING), Arrays.asList(SWAGGER, RETALIATE, UPROAR, FALSE_SWIPE), Arrays.asList(REVERSAL, BRICK_BREAK, BULK_UP, LOW_KICK), Arrays.asList(BRAVE_BIRD, BRAVE_BIRD, FEATHER_DANCE, SKY_ATTACK));
    public static Pokemon DEDENNE = KalosPokemon.register(702, "dedenne", 2, 67, 58, 57, 101, 151, Arrays.asList(ELECTRIC, FAIRY), Arrays.asList(SNORE, CUT, RETALIATE, LAST_RESORT), Arrays.asList(THUNDER, ELECTROWEB, THUNDER, MAGNET_RISE), Arrays.asList(CHARM, PLAY_ROUGH, DAZZLING_GLEAM, DRAINING_KISS));
    public static Pokemon CARBINK = KalosPokemon.register(703, "carbink", 3, 50, 50, 150, 50, 100, Arrays.asList(ROCK, FAIRY), Arrays.asList(FRUSTRATION, TAKE_DOWN, CONFIDE, ENDEAVOR), Arrays.asList(ANCIENT_POWER, SMACK_DOWN, ROCK_POLISH, ROCK_SLIDE), Arrays.asList(MOONBLAST, MOONBLAST, MISTY_TERRAIN, DAZZLING_GLEAM));
    public static Pokemon GOOMY = KalosPokemon.register(704, "goomy", 3, 45, 50, 35, 40, 60, Arrays.asList(DRAGON), Arrays.asList(PROTECT, SNORE, HIDDEN_POWER, SNORE), Arrays.asList(OUTRAGE, DRAGON_BREATH, DRAGON_PULSE, DRAGON_BREATH), Arrays.asList());
    public static Pokemon SLIGGOO = KalosPokemon.register(705, "sliggoo", 8, 68, 75, 53, 60, 158, Arrays.asList(DRAGON), Arrays.asList(RETURN, ATTRACT, PROTECT, CONFIDE), Arrays.asList(OUTRAGE, DRAGON_BREATH, OUTRAGE, DRAGON_BREATH), Arrays.asList());
    public static Pokemon GOODRA = KalosPokemon.register(706, "goodra", 20, 90, 100, 70, 80, 300, Arrays.asList(DRAGON), Arrays.asList(HIDDEN_POWER, HIDDEN_POWER, FACADE, TACKLE), Arrays.asList(DRACO_METEOR, DRAGON_PULSE, DRAGON_PULSE, DRAGON_PULSE), Arrays.asList());
    public static Pokemon KLEFKI = KalosPokemon.register(707, "klefki", 2, 57, 80, 91, 75, 165, Arrays.asList(STEEL, FAIRY), Arrays.asList(ENDURE, DOUBLE_TEAM, FRUSTRATION, CUT), Arrays.asList(MIRROR_SHOT, METAL_SOUND, FLASH_CANNON, IRON_DEFENSE), Arrays.asList(PLAY_ROUGH, CRAFTY_SHIELD, DRAINING_KISS, CRAFTY_SHIELD));
    public static Pokemon PHANTUMP = KalosPokemon.register(708, "phantump", 4, 43, 70, 48, 38, 62, Arrays.asList(GHOST, GRASS), Arrays.asList(ATTRACT, ROUND, CONFIDE, NATURE_POWER), Arrays.asList(SPITE, CURSE, CONFUSE_RAY, PHANTOM_FORCE), Arrays.asList(LEECH_SEED, WOOD_HAMMER, WORRY_SEED, SEED_BOMB));
    public static Pokemon TREVENANT = KalosPokemon.register(709, "trevenant", 15, 85, 110, 76, 56, 166, Arrays.asList(GHOST, GRASS), Arrays.asList(ENDURE, ROUND, GROWTH, SLEEP_TALK), Arrays.asList(DESTINY_BOND, SHADOW_CLAW, CURSE, PHANTOM_FORCE), Arrays.asList(ENERGY_BALL, WORRY_SEED, LEECH_SEED, WORRY_SEED));
    public static Pokemon PUMPKABOO_AVERAGE = KalosPokemon.register(710, "pumpkaboo_average", 4, 49, 66, 70, 51, 67, Arrays.asList(GHOST, GRASS), Arrays.asList(SAFEGUARD, SWAGGER, ENDURE, RETURN), Arrays.asList(HEX, SPITE, SHADOW_BALL, TRICK_OR_TREAT), Arrays.asList(SEED_BOMB, SOLAR_BEAM, GRASS_KNOT, BULLET_SEED));
    public static Pokemon GOURGEIST_AVERAGE = KalosPokemon.register(711, "gourgeist_average", 9, 65, 90, 122, 84, 173, Arrays.asList(GHOST, GRASS), Arrays.asList(SCARY_FACE, PROTECT, SLEEP_TALK, CONFIDE), Arrays.asList(HEX, HEX, SHADOW_SNEAK, TRICK_OR_TREAT), Arrays.asList(WORRY_SEED, WORRY_SEED, GIGA_DRAIN, SOLAR_BEAM));
    public static Pokemon BERGMITE = KalosPokemon.register(712, "bergmite", 10, 55, 69, 85, 28, 61, Arrays.asList(ICE), Arrays.asList(SNORE, BODY_SLAM, AFTER_YOU, TAKE_DOWN), Arrays.asList(ICICLE_SPEAR, HAIL, ICICLE_SPEAR, HAIL), Arrays.asList());
    public static Pokemon AVALUGG = KalosPokemon.register(713, "avalugg", 20, 95, 117, 184, 28, 180, Arrays.asList(ICE), Arrays.asList(STRENGTH, SLEEP_TALK, CONFIDE, BODY_SLAM), Arrays.asList(AVALANCHE, ICICLE_CRASH, ICE_BEAM, ICE_BEAM), Arrays.asList());
    public static Pokemon NOIBAT = KalosPokemon.register(714, "noibat", 5, 40, 30, 35, 55, 49, Arrays.asList(FLYING, DRAGON), Arrays.asList(SUPER_FANG, ROUND, RETURN, PROTECT), Arrays.asList(WING_ATTACK, WING_ATTACK, TAILWIND, TAILWIND), Arrays.asList(DRACO_METEOR, OUTRAGE, DRAGON_PULSE, DRAGON_PULSE));
    public static Pokemon NOIVERN = KalosPokemon.register(715, "noivern", 15, 85, 70, 80, 123, 187, Arrays.asList(FLYING, DRAGON), Arrays.asList(RETURN, RAZOR_WIND, SECRET_POWER, FRUSTRATION), Arrays.asList(AERIAL_ACE, GUST, AIR_CUTTER, AERIAL_ACE), Arrays.asList(DRAGON_DANCE, DRAGON_CLAW, DRAGON_TAIL, DRAGON_PULSE));
    public static Pokemon XERNEAS_ACTIVE = KalosPokemon.register(716, "xerneas_active", 30, 126, 131, 95, 99, 340, Arrays.asList(FAIRY), Arrays.asList(SWAGGER, SECRET_POWER, RETURN, DOUBLE_TEAM), Arrays.asList(DRAINING_KISS, DRAINING_KISS, DAZZLING_GLEAM, PLAY_ROUGH), Arrays.asList());
    public static Pokemon YVELTAL = KalosPokemon.register(717, "yveltal", 58, 126, 131, 95, 99, 340, Arrays.asList(DARK, FLYING), Arrays.asList(BODY_SLAM, SWAGGER, PROTECT, SLEEP_TALK), Arrays.asList(TAUNT, TORMENT, PAYBACK, DARK_PULSE), Arrays.asList(ROOST, DEFOG, GUST, OBLIVION_WING));
    public static Pokemon ZYGARDE_50 = KalosPokemon.register(718, "zygarde_50", 50, 108, 100, 121, 95, 300, Arrays.asList(DRAGON, GROUND), Arrays.asList(GLARE, PROTECT, SLEEP_TALK, SLEEP_TALK), Arrays.asList(DRAGON_DANCE, DRAGON_TAIL, OUTRAGE, DRAGON_PULSE), Arrays.asList(LANDS_WRATH, BULLDOZE, EARTH_POWER, EARTH_POWER));
    public static Pokemon DIANCIE = KalosPokemon.register(719, "diancie", 7, 50, 100, 150, 50, 300, Arrays.asList(ROCK, FAIRY), Arrays.asList(COVET, ENDURE, SHARPEN, COVET), Arrays.asList(ROCK_THROW, STONE_EDGE, STONE_EDGE, ANCIENT_POWER), Arrays.asList(PLAY_ROUGH, CHARM, DAZZLING_GLEAM, PLAY_ROUGH));
    public static Pokemon HOOPA = KalosPokemon.register(720, "hoopa", 5, 80, 110, 60, 70, 270, Arrays.asList(PokemonTypes.PSYCHIC, GHOST), Arrays.asList(HYPER_BEAM, SWIFT, GIGA_IMPACT, GIGA_IMPACT), Arrays.asList(REFLECT, REFLECT, REFLECT, CONFUSION), Arrays.asList(ASTONISH, SHADOW_BALL, PHANTOM_FORCE, DESTINY_BOND));
    public static Pokemon VOLCANION = KalosPokemon.register(721, "volcanion", 17, 80, 110, 120, 70, 300, Arrays.asList(FIRE, WATER), Arrays.asList(CONFIDE, HIDDEN_POWER, STRENGTH, WEATHER_BALL), Arrays.asList(FLAME_CHARGE, HEAT_WAVE, FLAME_CHARGE, FLAME_CHARGE), Arrays.asList(RAIN_DANCE, SCALD, STEAM_ERUPTION, RAIN_DANCE));


    public static Pokemon register(int id, String name, int height, int hp, int attack, int defence, int speed, int base_exp,
                                   List<PokemonType> types, List<PokemonMove> normal_moves, List<PokemonMove> t1_moves, List<PokemonMove> t2_moves){
        Pokemon pokemon = new Pokemon(id, name, height, hp, attack, defence, speed, base_exp, types, normal_moves, t1_moves, t2_moves);
        kalosPokemons.add(pokemon);
        return pokemon;
    }

}
